fixed mirror

diff --git a/docs/examples/mirror.in b/docs/examples/mirror.in
--- a/docs/examples/mirror.in
+++ b/docs/examples/mirror.in
@@ -6,46 +6,142 @@ set -eu
 
 # trace
 trace() { echo "mirror:DEBUG: $*"; }
+message() { echo "mirror:INFO: $*"; }
 error() { echo "mirror:ERROR: $*" >&2; exit 1; }
 die() { echo "mirror:FATAL: $*" >&2; exit 1; }
 
-# _mtab
-_mtab()
+trace "MIRROR: $0 $@"
+
+# _ismounted DIR
+_ismounted()
 {
-	local e="/^[^/]/d;
-             /^[ ]*$/d;"
-	local f
-    awk '{print $2}' /etc/mtab | sed -e "$e" | while read f; do
-		f="`readlink -e $f`" && test -e "$f" && echo "$f" || true
+	local dir="`readlink -e $1`" && test -d "$dir" \
+		|| die "_ismounted: invalid dir: '$1'"
+	local dir2
+	for dir2 in `awk '{print $2}' /etc/mtab`; do
+		dir2="`readlink -e $dir2`" && test -d "$dir2" \
+			|| continue
+		test x"$dir" != x"$dir2" || return 0
 	done
+	return 1
 }
 
-# _mount DEV|DIR
-_mount()
+# process_mount
+process_mount()
 {
-	local dir="$1"
-	if _mtab | grep "^${dir}\$" >/dev/null; then
-		trace "$dir is already mounted"
-	else
-		trace "mounting '$dir'"
-		if mount "$dir"; then
-			trace "OK"
-		else
-			die "could not mount '$dir'"
+	# 1. unmount RWMOUNT (weird things can happen if ROMOUNT is
+	# unmounted while RWMOUNT is still up)
+	if _ismounted "$RWMOUNT"; then
+		message "umount '$RWMOUNT'"
+		if ! umount "$RWMOUNT"; then
+			error "could not unmount '$RWMOUNT', trying lazy mode"
+			if ! umount -l "$RWMOUNT"; then
+				die "could not unmount '$RWMOUNT'"
+			fi
+		fi
+	fi
+	# 2. mount ROMOUNT if needed
+	if ! _ismounted "$ROMOUNT"; then
+		message "mount '$ROMOUNT'"
+		if ! mount "$ROMOUNT"; then
+			die "could not mount '$ROMOUNT'"
+		fi
+	fi
+	# 3. bind RWMOUNT and make it writable
+	message "mount --bind '$ROMOUNT' '$RWMOUNT'"
+	mount --bind "$ROMOUNT" "$RWMOUNT" \
+		|| die "could not bind '$RWMOUNT'"
+	message "mount -oremount,rw '$RWMOUNT'"
+	mount -oremount,rw "$RWMOUNT" \
+		|| die "could not set rw on '$RWMOUNT'"
+}
+
+# process_umount
+process_umount()
+{
+	# ?
+	if _ismounted "$RWMOUNT"; then
+		message "umount '$RWMOUNT'"
+		if ! umount "$RWMOUNT"; then
+			error "could not unmount '$RWMOUNT', trying lazy mode"
+			if ! umount -l "$RWMOUNT"; then
+				error "could not unmount '$RWMOUNT'"
+				return 1
+			fi
 		fi
 	fi
 }
 
-trace "MIRROR: $0 $@"
+# process_main
+process_main()
+{
+	# check stampfile
+	if test x"$STAMPFILE" = x; then
+		trace "no stampfile file given, sync forced"
+	else
+		test -e "$STAMPFILE" && OLDSTAMP="`cat $STAMPFILE`" || OLDSTAMP='X'
+		NEWSTAMP="`date '+%Y-%m-%d'`"
+		trace "stamps (old/new) : $OLDSTAMP/$NEWSTAMP"
+		if test x"$OLDSTAMP" = x"$NEWSTAMP"; then
+			trace "sync up to date, bye"
+			exit 0
+		else
+			trace "stamp mismatch, sync will be run"
+		fi
+	fi
+	# check files
+	L="$CHECK_FILES"
+	while test x"$L" != x; do
+		F="`echo $L | cut -d: -f1`"
+		L="`echo $L | cut -sd: -f2-`"
+		test x"$F" != x || continue
+		test -e "$F" \
+			&& trace "checkfile found: \`$F'" \
+			|| die "checkfile not found: \`$F'"
+	done
+	# ok, create the dest
+	test -d "$DEST" || mkdir -vp "$DEST"
+	#
+	RSYNC="`which rsync`" && test -x "$RSYNC" || die "rsync not found ($RSYNC)"
+	CMD="$RSYNC -a --delete --delete-excluded --numeric-ids --no-specials --one-file-system"
+	L="$EXCLUDE_FILES"
+	while test x"$L" != x; do
+		F="`echo $L | cut -d: -f1`"
+		L="`echo $L | cut -sd: -f2-`"
+		test x"$F" = x || CMD="${CMD} --exclude-from=\"$F\""
+	done
+	CMD="${CMD} \"$SOURCE/\" \"$DEST\""
+	# run
+	N=1
+	while true; do
+		R=0
+		trace "[$N/$NTRIES] `pwd`> $CMD"
+		eval "$CMD" || R=$?
+		case $R in
+			0) trace "rsync: success"; break;;
+			*) error "rsync: failed ($R)";;
+		esac
+		if test $N -ge $NTRIES; then
+			die "rsync failed $N times, giving up"
+		fi
+		N=$((N+1))
+	done
+	# update stampfile
+	trace "updating stampfile: \`$STAMPFILE'"
+	test x"$STAMPFILE" = x || {
+		echo "$NEWSTAMP" >"$STAMPFILE.tmp" \
+			&& mv -f "$STAMPFILE.tmp" "$STAMPFILE"; }
+}
 
 # defaults
 EXCLUDE_FILES=
 CHECK_FILES=
 NTRIES=3
 STAMPFILE=
-MNTDEVS=
+ROMOUNT=
+RWMOUNT=
 # parse command line
-GTO='getopt -s sh -n mirror -o "n:x:c:s:m:h" -- "${@}"' \
+GTO='getopt -s sh -n mirror -o "n:x:c:s:r:w:h" -- "${@}"' \
 	|| die "getopt failed"
 eval set -- "`eval $GTO`"
 while true; do
@@ -55,7 +151,8 @@ while true; do
 		-x) EXCLUDE_FILES="${EXCLUDE_FILES}:${2}"; shift 2;;
 		-c) CHECK_FILES="${CHECK_FILES}:${2}"; shift 2;;
 		-s) STAMPFILE="$2"; shift 2;;
-		-m) MNTDEVS="$MNTDEVS $2"; shift 2;;
+		-r) ROMOUNT="$2"; shift 2;;
+		-w) RWMOUNT="$2"; shift 2;;
 		--) shift; break;;
 		*) die "oups: arg $1"
 	esac
@@ -64,66 +161,16 @@ done
 test $# -eq 2 || die "wrong args number: $@"
 SOURCE="$1"
 DEST="$2"
-# mount
-for DEV in $MNTDEVS; do
-	trace "mounting '$DEV'"
-	_mount "$DEV" || die "could not mount '$DEV'"
-done
-# check stampfile
-if test x"$STAMPFILE" = x; then
-	trace "no stampfile file given, sync forced"
-else
-	test -e "$STAMPFILE" && OLDSTAMP="`cat $STAMPFILE`" || OLDSTAMP='X'
-	NEWSTAMP="`date '+%Y-%m-%d'`"
-	trace "stamps (old/new) : $OLDSTAMP/$NEWSTAMP"
-	if test x"$OLDSTAMP" = x"$NEWSTAMP"; then
-		trace "sync up to date, bye"
-		exit 0
-	else
-		trace "stamp mismatch, sync will be run"
-	fi
-fi
-# check files
-L="$CHECK_FILES"
-while test x"$L" != x; do
-	F="`echo $L | cut -d: -f1`"
-	L="`echo $L | cut -sd: -f2-`"
-	test x"$F" != x || continue
-	test -e "$F" \
-		&& trace "checkfile found: \`$F'" \
-		|| die "checkfile not found: \`$F'"
-done
-# ok, create the dest
-test -d "$DEST" || mkdir -vp "$DEST"
-#
-RSYNC="`which rsync`" && test -x "$RSYNC" || die "rsync not found ($RSYNC)"
-CMD="$RSYNC -a --delete --delete-excluded --numeric-ids --no-specials --one-file-system"
-L="$EXCLUDE_FILES"
-while test x"$L" != x; do
-	F="`echo $L | cut -d: -f1`"
-	L="`echo $L | cut -sd: -f2-`"
-	test x"$F" = x || CMD="${CMD} --exclude-from=\"$F\""
-done
-CMD="${CMD} \"$SOURCE/\" \"$DEST\""
-# run
-N=1
-while true; do
-	R=0
-	trace "[$N/$NTRIES] `pwd`> $CMD"
-	eval "$CMD" || R=$?
-	case $R in
-		0) trace "rsync: success"; break;;
-		*) error "rsync: failed ($R)";;
-	esac
-	if test $N -ge $NTRIES; then
-		die "rsync failed $N times, giving up"
-	fi
-	N=$((N+1))
-done
-# update stampfile
-trace "updating stampfile: \`$STAMPFILE'"
-test x"$STAMPFILE" = x || {
-	echo "$NEWSTAMP" >"$STAMPFILE.tmp" \
-		&& mv -f "$STAMPFILE.tmp" "$STAMPFILE"; }
-# ok
-trace "all done!"
+# mount ro/rw devices
+process_mount || die "mount(s) failed"
+# do the job
+RMAIN=0
+( process_main; ) || RMAIN=$?
+sync
+# umount rw
+process_umount || true
+# report
+test $RMAIN -eq 0 \
+	&& trace "all done!" \
+	|| error "failed!"
+exit $RMAIN
